- name: Download Putty installer to local install directory
  win_get_url:
    url: '{{ s3_url }}/software/putty/putty-64bit-0.72-installer.msi'
    dest: '{{ temp_folder }}\putty-64bit-0.72-installer.msi'
    proxy_url: '{{ proxy_url }}'
      
- name: Install Putty
  win_package:
    path: '{{ temp_folder }}\putty-64bit-0.72-installer.msi'
    product_id: 'Putty'
    state: present
    arguments: /quiet
