- name: Download AWS Workdocs installer to local install directory
  win_get_url:
    url: '{{ s3_url }}/software/workdocs/latest/AWSWorkDocsDriveClient.msi'
    dest: '{{ temp_folder }}\'

- name: Enable Window Windows Modules Installer
  win_service:
    name: TrustedInstaller
    state: started
    start_mode: manual

- name: Install AWS Workdocs
  win_package:
    path: '{{ temp_folder }}\AWSWorkDocsDriveClient.msi'
    product_id: 'AWSWorkDocsDriveClient'
    state: present
    arguments: REBOOT=REALLYSUPPRESS /norestart /qn
