---
- include_vars: '{{ provision_env }}.yml'

- name: Create temporary local install directory
  win_file:
    path: '{{ temp_folder }}'
    state: directory

- include_role:
    name: http_proxy

- include_tasks: apps/putty.yml

- include_tasks: cleanup.yml

