---
- include_vars: '{{ provision_env }}.yml'

- name: Create temporary local install directory
  win_file:
    path: '{{ temp_folder }}'
    state: directory

- include_tasks: apps/workdocs.yml
  when: install_action == 'install'

- include_tasks: apps/workdocs_update.yml
  when: install_action == 'update'

- include_tasks: cleanup.yml
