---
- include_vars: '{{ provision_env }}.yml'

- name: Create temporary local install directory
  win_file:
    path: '{{ temp_folder }}'
    state: directory

- include_tasks: apps/zoom-client.yml

- include_tasks: cleanup.yml
